# Generated by Django 5.1.5 on 2025-01-21 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Buyer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('age', models.CharField(max_length=3)),
                ('password', models.CharField(max_length=10)),
                ('email', models.CharField(max_length=50)),
            ],
        ),
    ]
